services:
  - type: web
    name: nexdefend-monolith
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: DB_PATH
        value: /data/nexdefend.db
      - key: JWT_SECRET_KEY
        generate: true
      - key: CORS_ALLOWED_ORIGINS
        value: https://nexdefend.vercel.app
      - key: PYTHON_API
        value: http://localhost:5000
      - key: OPENSEARCH_ADDR
        value: http://admin:Complexpass#123@localhost:4080
      - key: AI_SERVICE_TOKEN
        generate: true
    disk:
      name: nexdefend-data
      mountPath: /data
      sizeGB: 1
