{{- define "nexdefend.configmap" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nexdefend.fullname" . }}-config
  labels:
    {{- include "nexdefend.labels" . | nindent 4 }}
data:
  # ============================================================================
  # Global Environment Variables
  # ============================================================================
  # These values are shared across multiple services.
  dbHost: {{ .Values.config.dbHost | quote }}
  dbPort: {{ .Values.config.dbPort | quote }}
{{- end }}
