global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nexdefend-go'
    static_configs:
      - targets: ['api:8080']

  - job_name: 'nexdefend-python'
    static_configs:
      - targets: ['ai:5000']
