apiVersion: 1

datasources:
  - name: OpenSearch
    type: opensearch
    access: proxy
    url: http://opensearch:9200
    jsonData:
      database: '[logs-*-*]'
      timeField: '@timestamp'
    editable: true
